#   _________ __                      .__    .__
#  /   _____//  |______ _______  _____|  |__ |__|_____
#  \_____  \\   __\__  \\_  __ \/  ___/  |  \|  \____ \
#  /        \|  |  / __ \|  | \/\___ \|   Y  \  |  |_> >
# /_______  /|__| (____  /__|  /____  >___|  /__|   __/
#         \/           \/           \/     \/   |__|
#

# format = '$os $all' # Uncomment when showing hostname
format = '$all'

add_newline = true

palette = 'kanagawa'

[palettes.kanagawa]
color_fg = '#bf9663'
color_brown = '#7f745b'
color_gold = '#bfa95b'
color_lightyellow = '#d4c787'
color_turqoise = '#82c0af'
color_blue = '#29526e'
color_darkblue = '#171f40'
color_orange = '#d65d0e'

[character]
success_symbol = '[âœ](bold green)'
error_symbol = '[âœ—](bold red) '

[hostname]
ssh_only = true # show hostname
format = '[$ssh_symbol$hostname]($style) in '
style = 'fg:color_brown'

[os]
disabled = true # show OS symbol
style = 'fg:color_fg'

[os.symbols]
Windows = "ó°²"
Ubuntu = "ó°•ˆ"
Debian = "ó°£š"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’PICKING](bold red)'

[git_status]
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
up_to_date = 'âœ“'
stashed = 'ğŸ“¦'
staged = '[++\($count\)](green)'
deleted = 'ğŸ—‘'

[directory.substitutions]
"Downloads" = "ï€™ "
"Music" = "ó°š "
"Pictures" = "ï€¾ "
"Developer" = "ó°²‹ "

[nodejs]
symbol = "îœ˜ "

[c]
symbol = "î˜ "

[golang]
symbol = "î˜§ "
